package su.nsk.iae.post.generator.java.common;

import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class BaseProcessGenerator {
  public static String generate() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("import java.util.Map;");
    _builder.newLine();
    _builder.append("import java.util.List;");
    _builder.newLine();
    _builder.append("import java.util.HashMap;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public abstract class BaseProcess implements IProcess {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected final String instanceName;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected final Map<String,IProcess> processRefs = new HashMap<>();");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected final Map<String,Object> memory;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected final Map<String,String> aliases;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected final Map<String, IProcess> globalProcesses;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected BaseProcess(String instanceName, Map<String,Object> memory, ");
    _builder.newLine();
    _builder.append("    \t");
    _builder.append("Map<String,String> aliases, Map<String, IProcess> globalProcesses) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.instanceName = instanceName;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.memory = memory;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.aliases = aliases;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.globalProcesses = globalProcesses;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setProcess(String name, IProcess p) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("processRefs.put(name, p);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected IProcess getProcess(String name) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("IProcess p = processRefs.get(name);");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (p != null)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return p;");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("p = globalProcesses.get(name);");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (p != null)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return p;");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("throw new RuntimeException(\"Process not found: \" + name);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected String resolve(String name) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("String current = name;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (aliases != null) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("while (aliases.containsKey(current)) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("current = aliases.get(current);");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return current;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected Object read(String name) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return memory.get(resolve(name));");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected void writeVar(String name, Object value) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("memory.put(resolve(name), value);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected boolean isActive(IProcess p) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("String s = p.getStateName();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return !s.equals(\"Stop\") && !s.equals(\"Error\");");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected boolean isInactive(IProcess p) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("String s = p.getStateName();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return s.equals(\"Stop\") || s.equals(\"Error\");");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected boolean isStop(IProcess p) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return p.getStateName().equals(\"Stop\");");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected boolean isError(IProcess p) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return p.getStateName().equals(\"Error\");");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected boolean loopCond(String var, int end, int step) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("int value = ((Number)memory.get(var)).intValue();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return (step >= 0 && value <= end)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("|| (step < 0 && value >= end);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("// ===== SAFE READ =====");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected int readInt(String name) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("Object v = read(name);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (v instanceof Number)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return ((Number) v).intValue();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("throw new RuntimeException(\"Expected INT for \" + name + \", got \" + v);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected long readLong(String name) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("Object v = read(name);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (v instanceof Number)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return ((Number) v).longValue();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("throw new RuntimeException(\"Expected LONG for \" + name + \", got \" + v);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected double readDouble(String name) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("Object v = read(name);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (v instanceof Number)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return ((Number) v).doubleValue();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("throw new RuntimeException(\"Expected DOUBLE for \" + name + \", got \" + v);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected float readFloat(String name) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("Object v = read(name);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (v instanceof Number)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return ((Number) v).floatValue();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("throw new RuntimeException(\"Expected FLOAT for \" + name + \", got \" + v);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected boolean readBool(String name) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("Object v = read(name);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (v instanceof Boolean)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return (Boolean) v;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("throw new RuntimeException(\"Expected BOOL for \" + name + \", got \" + v);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected void setArrayValue(String name, int index, int start, Object value) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("memory.put(resolveArrayCell(name, index, start), value);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected Object getArrayValue(String name, int index, int start) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return memory.get(resolveArrayCell(name, index, start));");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected int getArrayInt(String name, int index, int start) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("Object v = getArrayValue(name, index, start);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (v instanceof Number)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return ((Number) v).intValue();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("throw new RuntimeException(\"Expected INT in array \" + name + \", got \" + v);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected long getArrayLong(String name, int index, int start) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("Object v = getArrayValue(name, index, start);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (v instanceof Number)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return ((Number) v).longValue();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("throw new RuntimeException(\"Expected LONG in array \" + name + \", got \" + v);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected float getArrayFloat(String name, int index, int start) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("Object v = getArrayValue(name, index, start);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (v instanceof Number)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return ((Number) v).floatValue();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("throw new RuntimeException(\"Expected FLOAT in array \" + name + \", got \" + v);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected double getArrayDouble(String name, int index, int start) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("Object v = getArrayValue(name, index, start);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (v instanceof Number)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return ((Number) v).doubleValue();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("throw new RuntimeException(\"Expected DOUBLE in array \" + name + \", got \" + v);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected boolean getArrayBool(String name, int index, int start) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("Object v = getArrayValue(name, index, start);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (v instanceof Boolean)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return (Boolean) v;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("throw new RuntimeException(\"Expected BOOL in array \" + name + \", got \" + v);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private String resolveArrayCell(String name, int index, int start) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("List<String> list = (List<String>) memory.get(resolve(name));");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("int offset = index - start;");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (offset < 0 || offset >= list.size()) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("throw new RuntimeException(");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("\"Array index out of bounds: \" + name + \"[\" + index + \"]\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return list.get(offset);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }
}
